.\" ARCHIVO DE AYUDA PARA EL MANUAL DE UNIX
.\" PARA LEER: man ./man_srpt.7
.\" O INSTALAR: sudo cp ./man_srpt /usr/share/man/man7/srpt.7 && sudo mandb
.\" Y LEER: man srpt
.TH man 7 "8 Jun 2017" "1.2" "Manual Script SistOp 2017"
.SH NAME
srpt \- Simulador de paginación y ejecución de procesos.
.SH SYNOPSIS
.B bash srpt.sh
[\fB\-s\fR]
[\fB\-f\fR \fIfile\fR]
[\fB\-m\fR \fInbloq\fR]
[\fB\-p\fR \fInproc\fR]
[\fB\-l\fR \fIlog\fR]
.SH DESCRIPTION
Acepta una serie de datos (a traves de fichero o teclado), donde se detalla los procesos que van a ser utilizados.
Realiza una representación grafica de la memoria, y va ocupando bloques de esta segun llegen los procesos.
Con el paso del tiempo los procesos terminan, se liberan y finaliza la ejecución.
.SH OPTIONS
.TP
.BR \-s ", " \-\-silencio "
Modo silencioso, no realiza ninguna representación gráfica.
.TP
.BR \-d ", " \-\-debug "
Modo debug, todos los tiempos son mostrados.
.TP
.BR \-f ", " \-\-filename "    " \fIfile\fR
Entrada por fichero, el valor file es interpretado como un archivo, incluir ruta si necesario.
.TP
.BR \-m ", " \-\-memoria "    " \fInbloq\fR
Tamaño en bloques de la memoria según el valor de nbloq. Este valor sobrescribe al dado en el fichero.
.TP
.BR \-p ", " \-\-procesos "    " \fInproc\fR
Número de procesos a pedir, no tiene efecto si es entrada por fichero.
.TP
.BR \-l ", " \-\-log "    " \fInivel\fR
Establece el nivel de salida por fichero (0=debug, 1=extendido, 2=estructural, 3=default, 4=alertas, 5=mínimo, 9=ejecucuión, 10=off).
.TP
.BR \-b ", " \-\-breakpoint "    " \fItiempo\fR
Habilita modo debug (y deshabilita modo silencioso) en el tiempo especificado.
.TP
.BR \-u ", " \-\-unbreakpoint "    " \fItiempo\fR
Deshabilita modo debug (y habilita modo silencioso si había sido habilitado) en el tiempo especificado.
.SH ENVIRONMENT
.TP
.BR input.txt
Fichero que contiene los datos a introducir, las configuraciones empiezan por (+), los comentarios por (#) y el resto son procesos (marcos;direcciones;tiempo{;ID}).
.SH exit
Devuelve 0 al terminar la ejecución, en caso de que se produzca un parada fatal, devuelve el código de error:
.TP
.BR 0
Ejecución correcta.
.TP
.BR 20
Siguiente proceso mayor que memoria.
.TP
.BR 30
Archivo de entrada no encontrado.
.TP
.BR 31
Configuración en archivo no válida.
.TP
.BR 40
Argumento de fichero no válido.
.TP
.BR 41
Argumento de memoria no válido.
.TP
.BR 42
Argumento de procesos no válido.
.TP
.BR 43
Argumento de log no válido.
.TP
.BR 44
Argumento de breakpoint no válido.
.TP
.BR 45
Argumento de unbreakpoint no válido.
.TP
.BR 90
Finalización voluntaria por versión anticuada.
.TP
.BR 91
Finalización voluntaria por ancho de pantalla.
.SH BUGS
No hay bugs, el código es perfecto y no puede ser cuestionado.
.SH AUTHOR
Roderick Diaz (about@rorik.me) (github.com/rorik)
